name: Tender Report Automation
on:
  push:
    paths:
      - 'inputs/**'
  schedule:
    - cron: '0 18 * * 1-5'  # Weekdays at 6 PM

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
         
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils libtesseract-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt --force-reinstall
          
      - name: Process documents
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/ocr_processor.py
          python scripts/report_generator.py
          
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: tender-reports
          path: outputs/
